/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorDetalleVentas;
import Controlador.ControladorVentas;
import javax.swing.JTextField;

/**
 *
 * @author cindy
 */
public class PanelVentas extends javax.swing.JPanel {

    private ControladorVentas controladorVentas;
    private ControladorDetalleVentas controladorDetalle;

    public PanelVentas() {
        initComponents();

        controladorVentas = new ControladorVentas(this);
        controladorDetalle = new ControladorDetalleVentas(this);
    }

    //esta parte solo funciona para correr este jframe
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame("Prueba - Cuentas por Pagar");
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new PanelVentas());
                frame.pack(); // ajusta tamaño al contenido
                frame.setSize(850, 700); // o fija el tamaño manualmente
                frame.setLocationRelativeTo(null); // centra la ventana
                frame.setVisible(true);
            }
        });
    }

    public JTextField getTxtImpuesto() {
        return txtImpuesto;
    }

    public void setTxtImpuesto(JTextField txtImpuesto) {
        this.txtImpuesto = txtImpuesto;
    }

    //esta parte solo funciona para correr este jframe     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondoPanel = new javax.swing.JPanel();
        marcaAgua = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelDescuentoSubsidio = new javax.swing.JLabel();
        labelObservaciones = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtIdVenta = new javax.swing.JTextField();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        scrollPanel = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnHacerVenta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        btnEliminarVenta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        IDCliente2 = new javax.swing.JLabel();
        txtIdDetalleVenta = new javax.swing.JTextField();
        IDCliente4 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        IDCliente1 = new javax.swing.JLabel();
        IDCliente5 = new javax.swing.JLabel();
        IDCliente6 = new javax.swing.JLabel();
        IDCliente7 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JPanel();
        actualizar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(850, 700));

        fondoPanel.setBackground(new java.awt.Color(28, 95, 118));
        fondoPanel.setPreferredSize(new java.awt.Dimension(850, 670));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 850, 20));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 850, 10));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NIT:");
        fondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Documento:");
        fondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 20));

        labelDescuentoSubsidio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelDescuentoSubsidio.setForeground(new java.awt.Color(255, 255, 255));
        labelDescuentoSubsidio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDescuentoSubsidio.setText("Total:");
        fondoPanel.add(labelDescuentoSubsidio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        labelObservaciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        labelObservaciones.setText("Observaciones:");
        fondoPanel.add(labelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha:");
        fondoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, -1));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("ID Venta:");
        fondoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Tipo de Pago:");
        fondoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 100, -1));

        txtNIT.setBackground(new java.awt.Color(75, 128, 146));
        txtNIT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNIT.setForeground(new java.awt.Color(255, 255, 255));
        txtNIT.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 170, -1));

        txtDocumento.setBackground(new java.awt.Color(75, 128, 146));
        txtDocumento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        fondoPanel.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, -1));

        txtTotal.setBackground(new java.awt.Color(75, 128, 146));
        txtTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 250, -1));

        txtFecha.setBackground(new java.awt.Color(75, 128, 146));
        txtFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, -1));

        txtIdVenta.setBackground(new java.awt.Color(75, 128, 146));
        txtIdVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtIdVenta.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentaActionPerformed(evt);
            }
        });
        fondoPanel.add(txtIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, -1));

        cmbMetodoPago.setBackground(new java.awt.Color(75, 128, 146));
        cmbMetodoPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cmbMetodoPago.setForeground(new java.awt.Color(255, 255, 255));
        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CREDITO" }));
        cmbMetodoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoPagoActionPerformed(evt);
            }
        });
        fondoPanel.add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, -1));

        txtObservaciones.setBackground(new java.awt.Color(75, 128, 146));
        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        txtObservaciones.setRows(5);
        txtObservaciones.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollPanel.setViewportView(txtObservaciones);

        fondoPanel.add(scrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 680, 70));

        btnHacerVenta.setBackground(new java.awt.Color(75, 128, 146));
        btnHacerVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hacer Venta");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnHacerVentaLayout = new javax.swing.GroupLayout(btnHacerVenta);
        btnHacerVenta.setLayout(btnHacerVentaLayout);
        btnHacerVentaLayout.setHorizontalGroup(
            btnHacerVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHacerVentaLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnHacerVentaLayout.setVerticalGroup(
            btnHacerVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHacerVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPanel.add(btnHacerVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 90, 40));

        labelSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        labelSubtotal.setText("ID Usuario:");
        fondoPanel.add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 100, 20));

        txtIdUsuario.setBackground(new java.awt.Color(75, 128, 146));
        txtIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, -1));

        btnEliminarVenta.setBackground(new java.awt.Color(75, 128, 146));
        btnEliminarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eliminar Venta");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnEliminarVentaLayout = new javax.swing.GroupLayout(btnEliminarVenta);
        btnEliminarVenta.setLayout(btnEliminarVentaLayout);
        btnEliminarVentaLayout.setHorizontalGroup(
            btnEliminarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarVentaLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        btnEliminarVentaLayout.setVerticalGroup(
            btnEliminarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPanel.add(btnEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 90, 40));

        titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("VENTAS");
        fondoPanel.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 850, -1));

        titulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("DETALLE DE VENTAS");
        fondoPanel.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 850, -1));

        IDCliente2.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente2.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente2.setText("ID Detalle Venta:");
        fondoPanel.add(IDCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, -1));

        txtIdDetalleVenta.setBackground(new java.awt.Color(75, 128, 146));
        txtIdDetalleVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdDetalleVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtIdDetalleVenta.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdDetalleVenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdDetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDetalleVentaActionPerformed(evt);
            }
        });
        fondoPanel.add(txtIdDetalleVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 360, -1));

        IDCliente4.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente4.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente4.setText("ID Producto:");
        fondoPanel.add(IDCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 100, -1));

        txtIdProducto.setBackground(new java.awt.Color(75, 128, 146));
        txtIdProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProducto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        fondoPanel.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 120, -1));

        IDCliente1.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente1.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente1.setText("Impuesto:");
        fondoPanel.add(IDCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 80, -1));

        IDCliente5.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente5.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente5.setText("Cantidad:");
        fondoPanel.add(IDCliente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 80, -1));

        IDCliente6.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente6.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente6.setText("Precio de Venta:");
        fondoPanel.add(IDCliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, -1));

        IDCliente7.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente7.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente7.setText("Descuento:");
        fondoPanel.add(IDCliente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 140, -1));

        txtImpuesto.setBackground(new java.awt.Color(75, 128, 146));
        txtImpuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtImpuesto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtImpuesto.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpuestoActionPerformed(evt);
            }
        });
        fondoPanel.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 130, -1));

        txtCantidad.setBackground(new java.awt.Color(75, 128, 146));
        txtCantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCantidad.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        fondoPanel.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 130, -1));

        txtPrecioVenta.setBackground(new java.awt.Color(75, 128, 146));
        txtPrecioVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        fondoPanel.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 130, -1));

        txtDescuento.setBackground(new java.awt.Color(75, 128, 146));
        txtDescuento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescuento.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        fondoPanel.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 130, -1));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizar.setText("Actualizar");
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 40));

        fondoPanel.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 90, 40));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Buscar.setText("BUSCAR");
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        fondoPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVentaActionPerformed

    private void cmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoPagoActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtIdDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetalleVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetalleVentaActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel IDCliente1;
    private javax.swing.JLabel IDCliente2;
    private javax.swing.JLabel IDCliente4;
    private javax.swing.JLabel IDCliente5;
    private javax.swing.JLabel IDCliente6;
    private javax.swing.JLabel IDCliente7;
    public javax.swing.JLabel actualizar;
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminarVenta;
    public javax.swing.JPanel btnHacerVenta;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelDescuentoSubsidio;
    public javax.swing.JLabel labelObservaciones;
    public javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel marcaAgua;
    public javax.swing.JScrollPane scrollPanel;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtDescuento;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtIdDetalleVenta;
    public javax.swing.JTextField txtIdProducto;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtIdVenta;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtNIT;
    public javax.swing.JTextArea txtObservaciones;
    public javax.swing.JTextField txtPrecioVenta;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
