/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;


import javax.swing.JTextField;
import controladores.ControladorCuentaPagar;
import Implementacion.CuentaPorPagarImpl;
/**
 *
 * @author cindy
 */
public class PanelCuentaPagar extends javax.swing.JPanel {
    
private ControladorCuentaPagar controlador;
private CuentaPorPagarImpl dao;

    /**
     * Creates new form PanelCuentaPagar
     */
    public PanelCuentaPagar() {
        initComponents();
        
    dao = new CuentaPorPagarImpl();
    controlador = new ControladorCuentaPagar(this, dao);
        
    }
    
    
    
    
    
    //--- metodos get y set para modificar los labels 

    public JTextField getTxtEstadoPago() {
        return txtEstadoPago;
    }

    public void setTxtEstadoPago(JTextField txtEstadoPago) {
        this.txtEstadoPago = txtEstadoPago;
    }

    public JTextField getTxtFechaEmision() {
        return txtFechaEmision;
    }

    public void setTxtFechaEmision(JTextField txtFechaEmision) {
        this.txtFechaEmision = txtFechaEmision;
    }

    public JTextField getTxtFechaVencimiento() {
        return txtFechaVencimiento;
    }

    public void setTxtFechaVencimiento(JTextField txtFechaVencimiento) {
        this.txtFechaVencimiento = txtFechaVencimiento;
    }

    public JTextField getTxtIdCompra() {
        return txtIdCompra;
    }

    public void setTxtIdCompra(JTextField txtIdCompra) {
        this.txtIdCompra = txtIdCompra;
    }

    public JTextField getTxtIdCuentaPago() {
        return txtIdCuentaPago;
    }

    public void setTxtIdCuentaPago(JTextField txtIdCuentaPago) {
        this.txtIdCuentaPago = txtIdCuentaPago;
    }

    public JTextField getTxtMontoTotal() {
        return txtMontoTotal;
    }

    public void setTxtMontoTotal(JTextField txtMontoTotal) {
        this.txtMontoTotal = txtMontoTotal;
    }

    public JTextField getTxtSaldoPendiente() {
        return txtSaldoPendiente;
    }

    public void setTxtSaldoPendiente(JTextField txtSaldoPendiente) {
        this.txtSaldoPendiente = txtSaldoPendiente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador = new javax.swing.JSeparator();
        IDCliente = new javax.swing.JLabel();
        txtIdCompra = new javax.swing.JTextField();
        IDCliente1 = new javax.swing.JLabel();
        IDCliente2 = new javax.swing.JLabel();
        IDCliente3 = new javax.swing.JLabel();
        IDCliente4 = new javax.swing.JLabel();
        IDCliente5 = new javax.swing.JLabel();
        IDCliente6 = new javax.swing.JLabel();
        txtEstadoPago = new javax.swing.JTextField();
        txtIdCuentaPago = new javax.swing.JTextField();
        txtFechaEmision = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtMontoTotal = new javax.swing.JTextField();
        txtSaldoPendiente = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("CUENTAS POR PAGAR");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        IDCliente.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente.setText("Estado de Pago:");
        add(IDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, -1));

        txtIdCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtIdCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdCompra.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCompraActionPerformed(evt);
            }
        });
        add(txtIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, -1));

        IDCliente1.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente1.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente1.setText("ID Cuenta de Pago:");
        add(IDCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, -1));

        IDCliente2.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente2.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente2.setText("ID Compra:");
        add(IDCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 130, -1));

        IDCliente3.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente3.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente3.setText("Fecha de Emisión:");
        add(IDCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, -1));

        IDCliente4.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente4.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente4.setText("Fecha de Vencimiento:");
        add(IDCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, -1));

        IDCliente5.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente5.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente5.setText("Monto Total:");
        add(IDCliente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 120, -1));

        IDCliente6.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente6.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente6.setText("Saldo Pendiente:");
        add(IDCliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 120, -1));

        txtEstadoPago.setBackground(new java.awt.Color(75, 128, 146));
        txtEstadoPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtEstadoPago.setForeground(new java.awt.Color(255, 255, 255));
        txtEstadoPago.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEstadoPago.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtEstadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoPagoActionPerformed(evt);
            }
        });
        add(txtEstadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 380, -1));

        txtIdCuentaPago.setBackground(new java.awt.Color(75, 128, 146));
        txtIdCuentaPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdCuentaPago.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCuentaPago.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdCuentaPago.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdCuentaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCuentaPagoActionPerformed(evt);
            }
        });
        add(txtIdCuentaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 130, -1));

        txtFechaEmision.setBackground(new java.awt.Color(75, 128, 146));
        txtFechaEmision.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFechaEmision.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaEmision.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFechaEmision.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtFechaEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEmisionActionPerformed(evt);
            }
        });
        add(txtFechaEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 370, -1));

        txtFechaVencimiento.setBackground(new java.awt.Color(75, 128, 146));
        txtFechaVencimiento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFechaVencimiento.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaVencimiento.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFechaVencimiento.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVencimientoActionPerformed(evt);
            }
        });
        add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 340, -1));

        txtMontoTotal.setBackground(new java.awt.Color(75, 128, 146));
        txtMontoTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtMontoTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtMontoTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMontoTotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTotalActionPerformed(evt);
            }
        });
        add(txtMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 130, -1));

        txtSaldoPendiente.setBackground(new java.awt.Color(75, 128, 146));
        txtSaldoPendiente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtSaldoPendiente.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldoPendiente.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSaldoPendiente.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtSaldoPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoPendienteActionPerformed(evt);
            }
        });
        add(txtSaldoPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 130, -1));

        btneliminar.setBackground(new java.awt.Color(75, 128, 146));
        btneliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 30));

        btnagregar.setBackground(new java.awt.Color(75, 128, 146));
        btnagregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Agregar");
        btnagregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 110, 30));

        btnactualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnactualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setText("Actualizar");
        btnactualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCompraActionPerformed

    private void txtEstadoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoPagoActionPerformed

    private void txtIdCuentaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCuentaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCuentaPagoActionPerformed

    private void txtFechaEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEmisionActionPerformed

    private void txtFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoActionPerformed

    private void txtMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTotalActionPerformed

    private void txtSaldoPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoPendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoPendienteActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       controlador.eliminarCuenta();
  
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        controlador.agregarCuenta();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        controlador.actualizarCuenta();
    }//GEN-LAST:event_btnactualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDCliente;
    private javax.swing.JLabel IDCliente1;
    private javax.swing.JLabel IDCliente2;
    private javax.swing.JLabel IDCliente3;
    private javax.swing.JLabel IDCliente4;
    private javax.swing.JLabel IDCliente5;
    private javax.swing.JLabel IDCliente6;
    public javax.swing.JPanel btnSalir;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo1;
    public javax.swing.JTextField txtEstadoPago;
    public javax.swing.JTextField txtFechaEmision;
    public javax.swing.JTextField txtFechaVencimiento;
    public javax.swing.JTextField txtIdCompra;
    public javax.swing.JTextField txtIdCuentaPago;
    public javax.swing.JTextField txtMontoTotal;
    public javax.swing.JTextField txtSaldoPendiente;
    // End of variables declaration//GEN-END:variables
}
