/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.JTextField;
import controladores.ControladorAuditoria;

/**
 *
 * @author cindy
 */

//falta arreglar error con id que se agrega otro numero


public class PanelAuditoria extends javax.swing.JPanel {
    
   

    

    /**
     * Creates new form PanelAuditoria
     */
    public PanelAuditoria() {
        initComponents();
        
  //  ControladorAuditoria controlador = new ControladorAuditoria(this);
        
    }
    
    //agregar get y setters 

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public void setTxtFecha(JTextField txtFecha) {
        this.txtFecha = txtFecha;
    }

    public JTextField getTxtIdAuditoria() {
        return txtIdAuditoria;
    }

    public void setTxtIdAuditoria(JTextField txtIdAuditoria) {
        this.txtIdAuditoria = txtIdAuditoria;
    }

    public JTextField getTxtIdRegistro() {
        return txtIdRegistro;
    }

    public void setTxtIdRegistro(JTextField txtIdRegistro) {
        this.txtIdRegistro = txtIdRegistro;
    }

    public JTextField getTxtIdUsuario() {
        return txtIdUsuario;
    }

    public void setTxtIdUsuario(JTextField txtIdUsuario) {
        this.txtIdUsuario = txtIdUsuario;
    }

    public JTextField getTxtMotivo() {
        return txtMotivo;
    }

    public void setTxtMotivo(JTextField txtMotivo) {
        this.txtMotivo = txtMotivo;
    }

    public JTextField getTxtOperacion() {
        return txtOperacion;
    }

    public void setTxtOperacion(JTextField txtOperacion) {
        this.txtOperacion = txtOperacion;
    }

    public JTextField getTxtTipoCambio() {
        return txtTipoCambio;
    }

    public void setTxtTipoCambio(JTextField txtTipoCambio) {
        this.txtTipoCambio = txtTipoCambio;
    }
    
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdAuditoria = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTipoCambio = new javax.swing.JTextField();
        txtIdRegistro = new javax.swing.JTextField();
        txtOperacion = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        titulo1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID Auditoría:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 20));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 140, 20));

        txtIdAuditoria.setBackground(new java.awt.Color(75, 128, 146));
        txtIdAuditoria.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdAuditoria.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAuditoria.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, -1));

        txtFecha.setBackground(new java.awt.Color(75, 128, 146));
        txtFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 410, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tipo de Cambio");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 130, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ID Registro:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 20));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Operacion:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 20));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ID Usuario:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, 20));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Motivo:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 140, 20));

        txtTipoCambio.setBackground(new java.awt.Color(75, 128, 146));
        txtTipoCambio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTipoCambio.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoCambio.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 130, -1));

        txtIdRegistro.setBackground(new java.awt.Color(75, 128, 146));
        txtIdRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdRegistro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdRegistro.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 240, -1));

        txtOperacion.setBackground(new java.awt.Color(75, 128, 146));
        txtOperacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(255, 255, 255));
        txtOperacion.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 220, -1));

        txtIdUsuario.setBackground(new java.awt.Color(75, 128, 146));
        txtIdUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIdUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, -1));

        txtMotivo.setBackground(new java.awt.Color(75, 128, 146));
        txtMotivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(255, 255, 255));
        txtMotivo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMotivo.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 410, 100));

        titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("AUDITORÍA");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(75, 128, 146));
        btnLimpiar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo1;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtIdAuditoria;
    public javax.swing.JTextField txtIdRegistro;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtMotivo;
    public javax.swing.JTextField txtOperacion;
    public javax.swing.JTextField txtTipoCambio;
    // End of variables declaration//GEN-END:variables
 public void setControlador(controladores.ControladorAuditoria c) {
        btnBuscar.setActionCommand("BUSCAR");
        btnLimpiar.setActionCommand("Limpiar");
        btnBuscar.addActionListener(c);
        btnLimpiar.addActionListener(c);
       
    }}
