/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorImpuestos;

/**
 *
 * @author cindy
 */
public class PanelImpuestos extends javax.swing.JPanel {

    /**
     * Creates new form PanelImpuestos
     */
  
private boolean listenersRegistrados = false;


    public PanelImpuestos() {
        initComponents();
        
    long idUsuarioActual = 1L;
        ControladorImpuestos controlador = new ControladorImpuestos(this, idUsuarioActual);

     

        setControlador(controlador);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        txtIdImpuesto = new javax.swing.JTextField();
        txtNombreImpuesto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JPanel();
        registrar = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JPanel();
        borrar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTasa = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JPanel();
        registrar1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("IMPUESTOS");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 850, -1));

        txtIdImpuesto.setBackground(new java.awt.Color(75, 128, 146));
        txtIdImpuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtIdImpuesto.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, -1));

        txtNombreImpuesto.setBackground(new java.awt.Color(75, 128, 146));
        txtNombreImpuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreImpuesto.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtNombreImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 290, -1));

        btnRegistrar.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(110, 30));
        btnRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar.setText("Registrar");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 100, 20));

        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, 30));

        btnBorrar.setBackground(new java.awt.Color(75, 128, 146));
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrar.setText("Borrar");
        borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, 30));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Buscar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 110, 30));

        txtTasa.setBackground(new java.awt.Color(75, 128, 146));
        txtTasa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTasa.setForeground(new java.awt.Color(255, 255, 255));
        txtTasa.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 170, -1));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setPreferredSize(new java.awt.Dimension(110, 30));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        registrar1.setForeground(new java.awt.Color(255, 255, 255));
        registrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar1.setText("Actualizar");
        registrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 100, 20));

        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ID Impuesto:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 160, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tasa:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrar;
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnBorrar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnRegistrar;
    public javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JLabel registrar;
    private javax.swing.JLabel registrar1;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtIdImpuesto;
    public javax.swing.JTextField txtNombreImpuesto;
    public javax.swing.JTextField txtTasa;
    // End of variables declaration//GEN-END:variables

  

public void setControlador(Controlador.ControladorImpuestos controlador) {
    if (listenersRegistrados) return; 

    
    btnBuscar.addMouseListener(controlador);
    btnRegistrar.addMouseListener(controlador);
    btnBorrar.addMouseListener(controlador);

   
    jLabel9.addMouseListener(controlador);     
    registrar.addMouseListener(controlador);  
    borrar.addMouseListener(controlador);      

    
    btnRegistrar.setName("REGISTRAR"); registrar.setName("REGISTRAR");
    btnBuscar.setName("BUSCAR");       jLabel9.setName("BUSCAR");
    btnBorrar.setName("BORRAR");       borrar.setName("BORRAR");

    listenersRegistrados = true;


}
}
