/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author cindy
 */
public class PanelDetalleCompra extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetalleCompra
     */
    public PanelDetalleCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador = new javax.swing.JSeparator();
        IDCliente1 = new javax.swing.JLabel();
        IDCliente2 = new javax.swing.JLabel();
        IDCliente3 = new javax.swing.JLabel();
        IDCliente4 = new javax.swing.JLabel();
        IDCliente5 = new javax.swing.JLabel();
        IDCliente6 = new javax.swing.JLabel();
        IDCliente7 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        txtIdDetalleCompra = new javax.swing.JTextField();
        txtIdCompra = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        actualizar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        eliminar = new javax.swing.JLabel();
        IDCliente8 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("DETALLE DE COMPRAS");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        IDCliente1.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente1.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente1.setText("Impuesto:");
        add(IDCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 80, -1));

        IDCliente2.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente2.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente2.setText("ID Detalle Compra:");
        add(IDCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 140, -1));

        IDCliente3.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente3.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente3.setText("ID Compra:");
        add(IDCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, -1));

        IDCliente4.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente4.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente4.setText("ID Producto:");
        add(IDCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 100, -1));

        IDCliente5.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente5.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente5.setText("Cantidad:");
        add(IDCliente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 80, -1));

        IDCliente6.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente6.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente6.setText("Precio de Compra:");
        add(IDCliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, -1));

        IDCliente7.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente7.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente7.setText("Total:");
        add(IDCliente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 140, -1));

        txtImpuesto.setBackground(new java.awt.Color(75, 128, 146));
        txtImpuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtImpuesto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtImpuesto.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpuestoActionPerformed(evt);
            }
        });
        add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, -1));

        txtIdDetalleCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtIdDetalleCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdDetalleCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtIdDetalleCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdDetalleCompra.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDetalleCompraActionPerformed(evt);
            }
        });
        add(txtIdDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 360, -1));

        txtIdCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtIdCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdCompra.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCompraActionPerformed(evt);
            }
        });
        add(txtIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 120, -1));

        txtIdProducto.setBackground(new java.awt.Color(75, 128, 146));
        txtIdProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProducto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 120, -1));

        txtCantidad.setBackground(new java.awt.Color(75, 128, 146));
        txtCantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCantidad.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, -1));

        txtPrecioCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtPrecioCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtPrecioCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPrecioCompra.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });
        add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 130, -1));

        txtTotal.setBackground(new java.awt.Color(75, 128, 146));
        txtTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 360, -1));

        btnAgregar.setBackground(new java.awt.Color(75, 128, 146));
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 90, 30));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizar.setText("Actualizar");
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(75, 128, 146));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar.setText("Eliminar");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 90, 30));

        IDCliente8.setBackground(new java.awt.Color(255, 255, 255));
        IDCliente8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IDCliente8.setForeground(new java.awt.Color(255, 255, 255));
        IDCliente8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDCliente8.setText("Descuento:");
        add(IDCliente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, -1));

        txtDescuento.setBackground(new java.awt.Color(75, 128, 146));
        txtDescuento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescuento.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoActionPerformed

    private void txtIdDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetalleCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetalleCompraActionPerformed

    private void txtIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCompraActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDCliente1;
    private javax.swing.JLabel IDCliente2;
    private javax.swing.JLabel IDCliente3;
    private javax.swing.JLabel IDCliente4;
    private javax.swing.JLabel IDCliente5;
    private javax.swing.JLabel IDCliente6;
    private javax.swing.JLabel IDCliente7;
    private javax.swing.JLabel IDCliente8;
    public javax.swing.JLabel actualizar;
    public javax.swing.JLabel agregar;
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnSalir;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo1;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtDescuento;
    public javax.swing.JTextField txtIdCompra;
    public javax.swing.JTextField txtIdDetalleCompra;
    public javax.swing.JTextField txtIdProducto;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtPrecioCompra;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
