/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControladorVistaAdmin;
import Modelo.ModeloVistaAdmin;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author cindy
 */
public class VistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();

        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Pill Icon MT 1-100.png"));
        setIconImage(icono);

        ModeloVistaAdmin modelo = new ModeloVistaAdmin(this);
        ControladorVistaAdmin controlador = new ControladorVistaAdmin(modelo);

        setControlador(controlador);
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        marcaAgua = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        userAdmin = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnProductos = new javax.swing.JPanel();
        productos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JPanel();
        productos2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCompras = new javax.swing.JPanel();
        productos3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JPanel();
        productos4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRegistroUsuarios = new javax.swing.JPanel();
        usuarios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAuditoria = new javax.swing.JPanel();
        usuarios1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JPanel();
        reportes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JPanel();
        regresar = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        productos1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contenedorFondo = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        fondoIzquierda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, -1));

        bienvenida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");
        fondoPanel.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, -1));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Pill Red MT 2 150x150.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        userAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        userAdmin.setForeground(new java.awt.Color(255, 255, 255));
        userAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAdmin.setText("ADMIN");
        fondoPanel.add(userAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, -1));

        btnProductos.setBackground(new java.awt.Color(75, 128, 146));
        btnProductos.setForeground(new java.awt.Color(51, 51, 51));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnProductosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(255, 255, 255));
        productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos.setText("  Productos");
        btnProductos.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("📦");
        jLabel2.setToolTipText("");
        btnProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        fondoPanel.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 210, -1));

        btnProveedores.setBackground(new java.awt.Color(75, 128, 146));
        btnProveedores.setForeground(new java.awt.Color(51, 51, 51));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnProveedoresAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos2.setBackground(new java.awt.Color(255, 255, 255));
        productos2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos2.setForeground(new java.awt.Color(255, 255, 255));
        productos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos2.setText("   Proveedores");
        btnProveedores.add(productos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("✈️");
        jLabel8.setToolTipText("");
        btnProveedores.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 20, 30));

        fondoPanel.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 210, -1));

        btnCompras.setBackground(new java.awt.Color(75, 128, 146));
        btnCompras.setForeground(new java.awt.Color(51, 51, 51));
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnComprasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos3.setBackground(new java.awt.Color(255, 255, 255));
        productos3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos3.setForeground(new java.awt.Color(255, 255, 255));
        productos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos3.setText("  Compras");
        btnCompras.add(productos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("🛒");
        jLabel9.setToolTipText("");
        btnCompras.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 20, 30));

        fondoPanel.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 210, -1));

        btnVentas.setBackground(new java.awt.Color(75, 128, 146));
        btnVentas.setForeground(new java.awt.Color(51, 51, 51));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnVentasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos4.setBackground(new java.awt.Color(255, 255, 255));
        productos4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos4.setForeground(new java.awt.Color(255, 255, 255));
        productos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos4.setText("  Ventas");
        btnVentas.add(productos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("💲");
        jLabel10.setToolTipText("");
        btnVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        fondoPanel.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 210, 30));

        btnRegistroUsuarios.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistroUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarios.setText("  Usuarios");
        btnRegistroUsuarios.add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("👤");
        btnRegistroUsuarios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        fondoPanel.add(btnRegistroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 210, -1));

        btnAuditoria.setBackground(new java.awt.Color(75, 128, 146));
        btnAuditoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuditoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        usuarios1.setForeground(new java.awt.Color(255, 255, 255));
        usuarios1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarios1.setText("  Auditoría");
        btnAuditoria.add(usuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("🖋️");
        btnAuditoria.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        fondoPanel.add(btnAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 210, 30));

        btnReportes.setBackground(new java.awt.Color(75, 128, 146));
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("  Reportes");
        btnReportes.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("📝");
        btnReportes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, -4, 20, 40));

        fondoPanel.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 210, 30));

        btnRegresar.setBackground(new java.awt.Color(75, 128, 146));
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 90, 30));

        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        btnClientes.setBackground(new java.awt.Color(75, 128, 146));
        btnClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnClientesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos1.setBackground(new java.awt.Color(255, 255, 255));
        productos1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos1.setForeground(new java.awt.Color(255, 255, 255));
        productos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos1.setText("  Clientes");
        btnClientes.add(productos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("👤");
        jLabel7.setToolTipText("");
        btnClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        fondoPanel.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        contenedorFondo.setBackground(new java.awt.Color(28, 95, 118));
        contenedorFondo.setPreferredSize(new java.awt.Dimension(850, 655));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setMinimumSize(new java.awt.Dimension(30, 27));
        btnSalir.setPreferredSize(new java.awt.Dimension(30, 27));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        javax.swing.GroupLayout contenedorFondoLayout = new javax.swing.GroupLayout(contenedorFondo);
        contenedorFondo.setLayout(contenedorFondoLayout);
        contenedorFondoLayout.setHorizontalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorFondoLayout.createSequentialGroup()
                .addContainerGap(824, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenedorFondoLayout.setVerticalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(664, Short.MAX_VALUE))
        );

        fondoPanel.add(contenedorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 860, 700));

        fondoIzquierda.setBackground(new java.awt.Color(23, 75, 93));
        fondoIzquierda.setOpaque(true);
        fondoPanel.add(fondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondoPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnProductosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosAncestorAdded

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnClientesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnClientesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesAncestorAdded

    private void btnProveedoresAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnProveedoresAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresAncestorAdded

    private void btnComprasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnComprasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasAncestorAdded

    private void btnVentasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnVentasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    public javax.swing.JPanel btnAuditoria;
    public javax.swing.JPanel btnClientes;
    public javax.swing.JPanel btnCompras;
    public javax.swing.JPanel btnProductos;
    public javax.swing.JPanel btnProveedores;
    public javax.swing.JPanel btnRegistroUsuarios;
    public javax.swing.JPanel btnRegresar;
    public javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JPanel btnVentas;
    public javax.swing.JPanel contenedorFondo;
    private javax.swing.JLabel fondoIzquierda;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel productos1;
    private javax.swing.JLabel productos2;
    private javax.swing.JLabel productos3;
    private javax.swing.JLabel productos4;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel userAdmin;
    private javax.swing.JLabel usuarios;
    private javax.swing.JLabel usuarios1;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaAdmin controlador) {
        btnRegresar.addMouseListener(controlador);
        btnProductos.addMouseListener(controlador);
//        btnGestionInventario.addMouseListener(controlador);
        btnReportes.addMouseListener(controlador);
        btnRegistroUsuarios.addMouseListener(controlador);
//        btnComponentesProductos.addMouseListener(controlador);
        btnProveedores.addMouseListener(controlador);
    }
}

